CREATE TABLE history (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	symbol TEXT NOT NULL,
	shares INTEGER NOT NULL,
	share_price INTEGER NOT NULL,
	total INTEGER NOT NULL,
	"date" DATETIME DEFAULT CURRENT_TIMESTAMP
	);


CREATE TABLE stocks (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	symbol TEXT NOT NULL,
	shares INTEGER NOT NULL,
	"updateded" DATETIME DEFAULT CURRENT_TIMESTAMP
	);